apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "100Mbps"
  labels:
    app: wordpress
spec:
  #type: LoadBalancerを定義
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wordpress